# Generated by Django 5.1.7 on 2025-04-19 11:34

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_path),
        ),
    ]
