# Generated by Django 5.1.7 on 2025-04-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.CharField(choices=[('fresh', 'Fresh Foods'), ('grocery', 'Grocery Staples'), ('beverage', 'Beverages'), ('alcohol', 'Wines & Liquors'), ('dairy', 'Dairy & Deli'), ('meat', 'Meat & Seafood'), ('snacks', 'Snacks & Sweets'), ('baby', 'Baby Care'), ('health', 'Health & Beauty'), ('household', 'Household')], default='grocery', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='is_food',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
