# Generated by Django 5.1.7 on 2025-04-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.CharField(choices=[('fresh', 'Fresh Produce'), ('frozen', 'Frozen Foods'), ('pantry', 'Pantry Staples'), ('dairy', 'Dairy & Eggs'), ('meat', 'Meat & Seafood'), ('beverage', 'Beverages'), ('snacks', 'Snacks'), ('household', 'Household'), ('personal_care', 'Personal Care')], default='pantry', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category'),
        ),
    ]
