# Generated by Django 5.1.7 on 2025-04-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_category_options_remove_category_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='department',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_perishable',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
