# Generated by Django 5.2 on 2025-04-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventory_category_inventory_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='date_added',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit_type',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_empty', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('expired', 'Expired')], default='available', max_length=12)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit')),
            ],
        ),
    ]
