# Generated by Django 5.2 on 2025-04-23 06:28

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_date_added_inventory_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_image',
        ),
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_path),
        ),
    ]
