# Generated by Django 5.2 on 2025-04-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_product_name_inventory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
    ]
