# Generated by Django 5.2 on 2025-04-23 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
        ),
    ]
