# Generated by Django 5.2 on 2025-04-23 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stock_amount_per_unit_alter_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
