# Generated by Django 5.2 on 2025-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_created_date_alter_stock_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
