# Generated by Django 5.2 on 2025-04-23 14:42

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_inventory_created_date_alter_stock_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, default='products/default-noimage.jpg', null=True, upload_to=inventory.models.product_image_path),
        ),
    ]
