# Generated by Django 5.1.7 on 2025-04-24 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_inventory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
