# Generated by Django 5.1.7 on 2025-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stock_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, default='products/default-noimage.jpg', null=True, upload_to='product'),
        ),
    ]
