# Generated by Django 5.1.7 on 2025-04-28 12:17

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_inventory_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, default='products/default-noimage.jpg', null=True, upload_to=inventory.models.product_image_path),
        ),
    ]
