# Generated by Django 5.1.7 on 2025-05-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out stock', 'Out Stock'), ('expired', 'Expired')], default='available', max_length=12),
        ),
    ]
