# Generated by Django 5.1.7 on 2025-05-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_remove_profile_address_remove_profile_phone_number'),
        ('inventory', '0031_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
    ]
