# Generated by Django 5.1.7 on 2025-04-19 12:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to=accounts.models.profile_image_path),
        ),
    ]
