# Generated by Django 5.1.7 on 2025-04-28 12:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to=accounts.models.profile_image_path),
        ),
    ]
