# Generated by Django 5.1.7 on 2025-05-01 10:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.profile_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.profile_image_path),
        ),
    ]
