# Generated by Django 5.1.7 on 2025-05-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_delete_notifications'),
        ('order', '0005_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
